[package]
name = "imageflow_node"
version = "0.1.1"
authors = ["Lilith River <lilith@imazen.io>"]
edition = "2018"
license = "AGPL-3.0-or-later"
build = "build.rs"
exclude = ["artifacts.json", "index.node"]

[lib]
name = "imageflow_node"
crate-type = ["cdylib"]

[build-dependencies]
neon-build = "0.4.0"

[dependencies]
neon = "0.4.0"
diskus = "0.5.0"
num_cpus = "1.0"
humansize = "1.1"
imageflow_core = { git = "https://github.com/imazen/imageflow", tag="v1.3.6-rc36" }
imageflow_types = { git = "https://github.com/imazen/imageflow", tag="v1.3.6-rc36" }
